# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title get_changepoints
#'
#' @description Multiple Changepoint Detection using methods: OP, PELT, GeomFPOP.
#' @param data is a matrix of data (p-rows x n-columns, where p - dimension, n - length).
#' @param penalty is a value of penalty (a non-negative real number).
#' @param method is the algorithm: 'OP', 'PELT', 'GeomFPOP (rectangle:random/random)' or 'chFPOP'.
#' @param showNbCands is the logical parameter (if "true", than to show the number of candidates at each iteration).
#' @return a list of  elements  = (changes, means, UnpenalizedCost, NumberOfCandidates).
#'
#' \describe{
#' \item{\code{changes}}{is the changepoint vector that gives the last index of each segment for the p-variate time series.}
#' \item{\code{means}}{is the list of successive means for the p-variate time series.}
#' \item{\code{UnpenalizedCost}}{is a number equal to the global cost.}
#' \item{\code{NumberOfCandidates}}{is a number of candidates at each iteration (vector).}
#' }
#'
#' @examples
#' N <- 100000
#' Chpt <-5000
#' Means <-  matrix(c(0,1,1,10), nrow = 2) 
#' Noise <- 1
#' Dim <- 2
#' Penalty <- 2*Dim*log(N)
#' time_series <- rnormChanges(p = Dim, n = N, changes = Chpt, means = Means, noise = Noise)
#' time_series <- rnormChanges(p = 2, n = N, changes = NULL, means = matrix(0, ncol = 1, nrow = 2), noise = 1)
#' Dim <- 3
#' Penalty <- 2*Dim*log(N)
#' time_series <- rnormChanges(p = 3, n = N, changes = NULL, means = matrix(0, ncol = 1, nrow = 3), noise = 1)
#' get_changepoints(data = time_series, penalty = Penalty, method = 'OP',showNbCands = FALSE)
#' get_changepoints(data = time_series, penalty = Penalty, method = 'PELT', showNbCands = FALSE)
#' get_changepoints(data = time_series, penalty = Penalty, method = 'GeomFPOP', showNbCands = FALSE)
#' get_changepoints(data = time_series, penalty = Penalty, method = 'chFPOP', showNbCands = FALSE)
NULL

get_changepoints <- function(data, penalty, method = "GeomFPOP", showNbCands = FALSE) {
    .Call(`_chFPOP_get_changepoints`, data, penalty, method, showNbCands)
}

